// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_failures.sql

package repository

import (
	"context"
	"database/sql"
)

const createAlertFailure = `-- name: CreateAlertFailure :one
INSERT INTO alert_failures (material_id, alert_type, error)
VALUES($1, $2, $3)
RETURNING id, material_id, alert_type, error, created_at
`

type CreateAlertFailureParams struct {
	MaterialID sql.NullInt64 `json:"material_id"`
	AlertType  string        `json:"alert_type"`
	Error      string        `json:"error"`
}

func (q *Queries) CreateAlertFailure(ctx context.Context, arg CreateAlertFailureParams) (AlertFailure, error) {
	row := q.db.QueryRowContext(ctx, createAlertFailure, arg.MaterialID, arg.AlertType, arg.Error)
	var i AlertFailure
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.AlertType,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listAlertFailures = `-- name: ListAlertFailures :many
SELECT id, material_id, alert_type, error, created_at FROM alert_failures ORDER BY created_at DESC
`

func (q *Queries) ListAlertFailures(ctx context.Context) ([]AlertFailure, error) {
	rows, err := q.db.QueryContext(ctx, listAlertFailures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertFailure
	for rows.Next() {
		var i AlertFailure
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.AlertType,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
