// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package repository

import (
	"context"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (
    material_id,
    alert_type,
    message
) VALUES (
    $1, $2, $3
)
RETURNING
  id,
  material_id,
  alert_type,
  message,
  is_resolved,
  created_at,
  resolved_at
`

type CreateAlertParams struct {
	MaterialID int64  `json:"material_id"`
	AlertType  string `json:"alert_type"`
	Message    string `json:"message"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRowContext(ctx, createAlert, arg.MaterialID, arg.AlertType, arg.Message)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.AlertType,
		&i.Message,
		&i.IsResolved,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listUnresolvedAlerts = `-- name: ListUnresolvedAlerts :many
SELECT
    id,
    material_id,
    alert_type,
    message,
    is_resolved,
    created_at,
    resolved_at
FROM alerts
WHERE is_resolved = FALSE
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListUnresolvedAlerts(ctx context.Context) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listUnresolvedAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.AlertType,
			&i.Message,
			&i.IsResolved,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAlert = `-- name: ResolveAlert :one
UPDATE alerts
SET
    is_resolved = TRUE,
    resolved_at = NOW()
WHERE id = $1
RETURNING
    id,
    material_id,
    alert_type,
    message,
    is_resolved,
    created_at,
    resolved_at
`

func (q *Queries) ResolveAlert(ctx context.Context, id int64) (Alert, error) {
	row := q.db.QueryRowContext(ctx, resolveAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.AlertType,
		&i.Message,
		&i.IsResolved,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
