// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: materials.sql

package repository

import (
	"context"
	"database/sql"
)

const createMaterial = `-- name: CreateMaterial :one
INSERT INTO materials (
    code,
    name,
    category,
    unit,
    specification,
    supplier_id,
    quantity,
    min_stock,
    max_stock,
    unit_price,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING
  id,
  code,
  name,
  category,
  unit,
  specification,
  supplier_id,
  quantity,
  min_stock,
  max_stock,
  unit_price,
  status,
  created_at,
  updated_at
`

type CreateMaterialParams struct {
	Code          string         `json:"code"`
	Name          string         `json:"name"`
	Category      sql.NullString `json:"category"`
	Unit          string         `json:"unit"`
	Specification sql.NullString `json:"specification"`
	SupplierID    sql.NullInt64  `json:"supplier_id"`
	Quantity      string         `json:"quantity"`
	MinStock      string         `json:"min_stock"`
	MaxStock      sql.NullString `json:"max_stock"`
	UnitPrice     string         `json:"unit_price"`
	Status        string         `json:"status"`
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error) {
	row := q.db.QueryRowContext(ctx, createMaterial,
		arg.Code,
		arg.Name,
		arg.Category,
		arg.Unit,
		arg.Specification,
		arg.SupplierID,
		arg.Quantity,
		arg.MinStock,
		arg.MaxStock,
		arg.UnitPrice,
		arg.Status,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.Specification,
		&i.SupplierID,
		&i.Quantity,
		&i.MinStock,
		&i.MaxStock,
		&i.UnitPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaterialByID = `-- name: GetMaterialByID :one
SELECT
    id,
    code,
    name,
    category,
    unit,
    specification,
    supplier_id,
    quantity,
    min_stock,
    max_stock,
    unit_price,
    status,
    created_at,
    updated_at
FROM materials
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetMaterialByID(ctx context.Context, id int64) (Material, error) {
	row := q.db.QueryRowContext(ctx, getMaterialByID, id)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.Specification,
		&i.SupplierID,
		&i.Quantity,
		&i.MinStock,
		&i.MaxStock,
		&i.UnitPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMaterials = `-- name: ListMaterials :many
SELECT
    id,
    code,
    name,
    category,
    unit,
    specification,
    supplier_id,
    quantity,
    min_stock,
    max_stock,
    unit_price,
    status,
    created_at,
    updated_at
FROM materials
ORDER BY id DESC
`

func (q *Queries) ListMaterials(ctx context.Context) ([]Material, error) {
	rows, err := q.db.QueryContext(ctx, listMaterials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Material
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Category,
			&i.Unit,
			&i.Specification,
			&i.SupplierID,
			&i.Quantity,
			&i.MinStock,
			&i.MaxStock,
			&i.UnitPrice,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaterialQuantity = `-- name: UpdateMaterialQuantity :one
UPDATE materials
SET
    quantity = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    code,
    name,
    category,
    unit,
    specification,
    supplier_id,
    quantity,
    min_stock,
    max_stock,
    unit_price,
    status,
    created_at,
    updated_at
`

type UpdateMaterialQuantityParams struct {
	ID       int64  `json:"id"`
	Quantity string `json:"quantity"`
}

func (q *Queries) UpdateMaterialQuantity(ctx context.Context, arg UpdateMaterialQuantityParams) (Material, error) {
	row := q.db.QueryRowContext(ctx, updateMaterialQuantity, arg.ID, arg.Quantity)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.Specification,
		&i.SupplierID,
		&i.Quantity,
		&i.MinStock,
		&i.MaxStock,
		&i.UnitPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
