// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"
)

type Alert struct {
	ID         int64        `json:"id"`
	MaterialID int64        `json:"material_id"`
	AlertType  string       `json:"alert_type"`
	Message    string       `json:"message"`
	IsResolved bool         `json:"is_resolved"`
	CreatedAt  time.Time    `json:"created_at"`
	ResolvedAt sql.NullTime `json:"resolved_at"`
}

type Material struct {
	ID            int64          `json:"id"`
	Code          string         `json:"code"`
	Name          string         `json:"name"`
	Category      sql.NullString `json:"category"`
	Unit          string         `json:"unit"`
	Specification sql.NullString `json:"specification"`
	SupplierID    sql.NullInt64  `json:"supplier_id"`
	Quantity      string         `json:"quantity"`
	MinStock      string         `json:"min_stock"`
	MaxStock      sql.NullString `json:"max_stock"`
	UnitPrice     string         `json:"unit_price"`
	Status        string         `json:"status"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type StockMovement struct {
	ID           int64          `json:"id"`
	MaterialID   int64          `json:"material_id"`
	MovementType string         `json:"movement_type"`
	Quantity     string         `json:"quantity"`
	UnitPrice    string         `json:"unit_price"`
	ReferenceNo  sql.NullString `json:"reference_no"`
	Remark       sql.NullString `json:"remark"`
	OperatorID   sql.NullInt64  `json:"operator_id"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Stocktaking struct {
	ID         int64          `json:"id"`
	Period     string         `json:"period"`
	Status     string         `json:"status"`
	OperatorID sql.NullInt64  `json:"operator_id"`
	Remark     sql.NullString `json:"remark"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type StocktakingItem struct {
	ID             int64          `json:"id"`
	StocktakingID  int64          `json:"stocktaking_id"`
	MaterialID     int64          `json:"material_id"`
	BookQuantity   string         `json:"book_quantity"`
	ActualQuantity string         `json:"actual_quantity"`
	Difference     sql.NullString `json:"difference"`
	CreatedAt      time.Time      `json:"created_at"`
}

type Supplier struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	ContactPerson sql.NullString `json:"contact_person"`
	Phone         sql.NullString `json:"phone"`
	Email         sql.NullString `json:"email"`
	Address       sql.NullString `json:"address"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
