// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	AddStocktakingItem(ctx context.Context, arg AddStocktakingItemParams) (StocktakingItem, error)
	ConfirmStocktaking(ctx context.Context, id int64) (Stocktaking, error)
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error)
	CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (StockMovement, error)
	CreateStocktaking(ctx context.Context, arg CreateStocktakingParams) (Stocktaking, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FilterMaterials(ctx context.Context, arg FilterMaterialsParams) ([]Material, error)
	FilterMovements(ctx context.Context, arg FilterMovementsParams) ([]StockMovement, error)
	GetMaterialByID(ctx context.Context, id int64) (Material, error)
	GetMonthlyReport(ctx context.Context, arg GetMonthlyReportParams) ([]GetMonthlyReportRow, error)
	GetStocktakingByID(ctx context.Context, id int64) (Stocktaking, error)
	GetSupplierByID(ctx context.Context, id int64) (Supplier, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListStockMovements(ctx context.Context) ([]StockMovement, error)
	ListStocktaking(ctx context.Context) ([]Stocktaking, error)
	ListStocktakingItems(ctx context.Context, stocktakingID int64) ([]StocktakingItem, error)
	ListSuppliers(ctx context.Context) ([]Supplier, error)
	ListUnresolvedAlerts(ctx context.Context) ([]Alert, error)
	ListUsers(ctx context.Context) ([]User, error)
	ResolveAlert(ctx context.Context, id int64) (Alert, error)
	UpdateMaterialQuantity(ctx context.Context, arg UpdateMaterialQuantityParams) (Material, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
