// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stocktaking.sql

package repository

import (
	"context"
	"database/sql"
)

const addStocktakingItem = `-- name: AddStocktakingItem :one
INSERT INTO stocktaking_items (
    stocktaking_id,
    material_id,
    book_quantity,
    actual_quantity
) VALUES (
    $1, $2, $3, $4
)
RETURNING
    id,
    stocktaking_id,
    material_id,
    book_quantity,
    actual_quantity,
    difference,
    created_at
`

type AddStocktakingItemParams struct {
	StocktakingID  int64  `json:"stocktaking_id"`
	MaterialID     int64  `json:"material_id"`
	BookQuantity   string `json:"book_quantity"`
	ActualQuantity string `json:"actual_quantity"`
}

func (q *Queries) AddStocktakingItem(ctx context.Context, arg AddStocktakingItemParams) (StocktakingItem, error) {
	row := q.db.QueryRowContext(ctx, addStocktakingItem,
		arg.StocktakingID,
		arg.MaterialID,
		arg.BookQuantity,
		arg.ActualQuantity,
	)
	var i StocktakingItem
	err := row.Scan(
		&i.ID,
		&i.StocktakingID,
		&i.MaterialID,
		&i.BookQuantity,
		&i.ActualQuantity,
		&i.Difference,
		&i.CreatedAt,
	)
	return i, err
}

const confirmStocktaking = `-- name: ConfirmStocktaking :one
UPDATE stocktaking
SET
    status = 'confirmed',
    updated_at = NOW()
WHERE id = $1
    AND status = 'draft'
RETURNING
    id,
    period,
    status,
    operator_id,
    remark,
    created_at,
    updated_at
`

func (q *Queries) ConfirmStocktaking(ctx context.Context, id int64) (Stocktaking, error) {
	row := q.db.QueryRowContext(ctx, confirmStocktaking, id)
	var i Stocktaking
	err := row.Scan(
		&i.ID,
		&i.Period,
		&i.Status,
		&i.OperatorID,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStocktaking = `-- name: CreateStocktaking :one
INSERT INTO stocktaking (
    period,
    status,
    operator_id,
    remark
) VALUES (
    $1, $2, $3, $4
)
RETURNING
  id,
  period,
  status,
  operator_id,
  remark,
  created_at,
  updated_at
`

type CreateStocktakingParams struct {
	Period     string         `json:"period"`
	Status     string         `json:"status"`
	OperatorID sql.NullInt64  `json:"operator_id"`
	Remark     sql.NullString `json:"remark"`
}

func (q *Queries) CreateStocktaking(ctx context.Context, arg CreateStocktakingParams) (Stocktaking, error) {
	row := q.db.QueryRowContext(ctx, createStocktaking,
		arg.Period,
		arg.Status,
		arg.OperatorID,
		arg.Remark,
	)
	var i Stocktaking
	err := row.Scan(
		&i.ID,
		&i.Period,
		&i.Status,
		&i.OperatorID,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStocktakingByID = `-- name: GetStocktakingByID :one
SELECT
    id,
    period,
    status,
    operator_id,
    remark,
    created_at,
    updated_at
FROM stocktaking
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetStocktakingByID(ctx context.Context, id int64) (Stocktaking, error) {
	row := q.db.QueryRowContext(ctx, getStocktakingByID, id)
	var i Stocktaking
	err := row.Scan(
		&i.ID,
		&i.Period,
		&i.Status,
		&i.OperatorID,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStocktaking = `-- name: ListStocktaking :many
SELECT
    id,
    period,
    status,
    operator_id,
    remark,
    created_at,
    updated_at
FROM stocktaking
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListStocktaking(ctx context.Context) ([]Stocktaking, error) {
	rows, err := q.db.QueryContext(ctx, listStocktaking)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stocktaking
	for rows.Next() {
		var i Stocktaking
		if err := rows.Scan(
			&i.ID,
			&i.Period,
			&i.Status,
			&i.OperatorID,
			&i.Remark,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStocktakingItems = `-- name: ListStocktakingItems :many
SELECT
    id,
    stocktaking_id,
    material_id,
    book_quantity,
    actual_quantity,
    difference,
    created_at
FROM stocktaking_items
WHERE stocktaking_id = $1
ORDER BY id
`

func (q *Queries) ListStocktakingItems(ctx context.Context, stocktakingID int64) ([]StocktakingItem, error) {
	rows, err := q.db.QueryContext(ctx, listStocktakingItems, stocktakingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StocktakingItem
	for rows.Next() {
		var i StocktakingItem
		if err := rows.Scan(
			&i.ID,
			&i.StocktakingID,
			&i.MaterialID,
			&i.BookQuantity,
			&i.ActualQuantity,
			&i.Difference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
