// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const createStockMovement = `-- name: CreateStockMovement :one
INSERT INTO stock_movements (
    material_id,
    movement_type,
    quantity,
    unit_price,
    reference_no,
    remark,
    operator_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING
  id,
  material_id,
  movement_type,
  quantity,
  unit_price,
  reference_no,
  remark,
  operator_id,
  created_at
`

type CreateStockMovementParams struct {
	MaterialID   int64          `json:"material_id"`
	MovementType string         `json:"movement_type"`
	Quantity     string         `json:"quantity"`
	UnitPrice    string         `json:"unit_price"`
	ReferenceNo  sql.NullString `json:"reference_no"`
	Remark       sql.NullString `json:"remark"`
	OperatorID   sql.NullInt64  `json:"operator_id"`
}

func (q *Queries) CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (StockMovement, error) {
	row := q.db.QueryRowContext(ctx, createStockMovement,
		arg.MaterialID,
		arg.MovementType,
		arg.Quantity,
		arg.UnitPrice,
		arg.ReferenceNo,
		arg.Remark,
		arg.OperatorID,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.MovementType,
		&i.Quantity,
		&i.UnitPrice,
		&i.ReferenceNo,
		&i.Remark,
		&i.OperatorID,
		&i.CreatedAt,
	)
	return i, err
}

const getMonthlyReport = `-- name: GetMonthlyReport :many
SELECT
    material_id,
    movement_type,
    SUM(quantity) AS total_quantity,
    SUM(quantity * unit_price) AS total_amount
FROM stock_movements
WHERE created_at >= $1
    AND created_at < $2
GROUP BY material_id, movement_type
ORDER BY material_id, movement_type
`

type GetMonthlyReportParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetMonthlyReportRow struct {
	MaterialID    int64  `json:"material_id"`
	MovementType  string `json:"movement_type"`
	TotalQuantity int64  `json:"total_quantity"`
	TotalAmount   int64  `json:"total_amount"`
}

func (q *Queries) GetMonthlyReport(ctx context.Context, arg GetMonthlyReportParams) ([]GetMonthlyReportRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyReport, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyReportRow
	for rows.Next() {
		var i GetMonthlyReportRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.MovementType,
			&i.TotalQuantity,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovements = `-- name: ListStockMovements :many
SELECT
    id,
    material_id,
    movement_type,
    quantity,
    unit_price,
    reference_no,
    remark,
    operator_id,
    created_at
FROM stock_movements
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListStockMovements(ctx context.Context) ([]StockMovement, error) {
	rows, err := q.db.QueryContext(ctx, listStockMovements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.MovementType,
			&i.Quantity,
			&i.UnitPrice,
			&i.ReferenceNo,
			&i.Remark,
			&i.OperatorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
